spring:
  datasource:
    # druid-spring-boot-starter?????? druid?????? type ????????
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.1.182:3306/aigc_base?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=UTC
    username: mysql
    password: MySQL_2024

    #Druid????????druid-spring-boot-starter????????????
    initialSize: 5
    minIdle: 5
    maxActive: 20
    maxWait: 60000
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: SELECT 1 FROM DUAL
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: false
    maxPoolPreparedStatementPerConnectionSize: 20
    useGlobalDataSourceStat: true
    # ?????????filters????????sql?????stat:???? log4:???? wall:??sql??
    # ????????ClassNotFoundException:orgapache.log4j.Priority????log4j????
    filters: stat,wall